version: '3'
services:
  client:
    build:
      context: ./client
    ports:
      - "8080:8080"
    links:
    - server
  server:
    build:
      context: ./server
    ports:
    - "8000:8000"
    - "8001:8001"
